app:
  version: 1.0.0
spring:
  application:
    name: book-catalog
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    enabled: true
    tryItOutEnabled: true
    filter: true
    tags-sorter: alpha
  api-docs:
    path: /api-docs
    enabled: true
  packages-to-scan: com.moneygram.book_catalog.presentation.controller
